# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38b9b93edba5cecfaa3796f24e97bb0b0ed1ac719253e3bda3b10ce19092e588d8f6e66ffb6b8866531c8c6270d5fd1b1d52f3d5d5a44d7520c93774afe6317a

test:
  secret_key_base: 9e0663a0ba5aabe113d1fbf4afb50e6091219a2a08ae5607a557109bc004e5925415f2223a021c43acffaaeaad0d82acd2d65c8bbc2daccfecb835e6ba528446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
